language: python

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install beautifulsoup4 coverage coveralls

script:
  coverage run --source=flask_triangle tests/run.py

after_success:
  coveralls
